interface handler {
    use jabratech:common/types.{response};
    use types.{interpolator-iv-request, interpolator-iv-response, interpolator-config-request, interpolator-config-response, interpolator-data-request, interpolator-data-response};

    get-iv: func(request: interpolator-iv-request) -> result<interpolator-iv-response, response>;
    get-config: func(request: interpolator-config-request) -> result<interpolator-config-response, response>;
    get-data: func(request: interpolator-data-request) -> result<interpolator-data-response, response>;
}