interface types {
    record interpolator-iv-request {
        date: string,
        currency: s8
    }

    record interpolator-iv-response {
        code: s16,
        message: string,
        iv: f64
    }
}